name: 'Clair Scan Clair'
description: 'Report Clair scan results as annotations on Github Pull Request [clair]'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  token:
    description: 'Specify the token to use to publish the check.'
    required: false
    default: ${{ github.token }}
  github_token:
    description: 'Deprecated syntax to specify github token.'
    required: true
  report_paths:
    description: 'Scan json report paths in glob format'
    required: true
  check_name:
    description: 'Check name for test reports.'
    required: false
    default: 'Clair Scan Report'
  commit:
    description: 'Commit SHA to update the check status.'
    required: false
  fail_with_vulnerabilities:
    description: 'By default not failed if found vulnerabilities with severity >= High. If true Mark as failure if exist high vulnerabilities'
    required: false
    default: 'false'
  require_scans:
    description: 'Fail if no json scan is found.'
    required: false
    default: 'false'
  summary:
    description: 'Additional text to summary output'
    required: false
    default: ''
  severity_level:
    description: 'Severity Level to publish scan'
    required: false
    default: 'High'
  publish_summary:
    description: 'Forced the Publication Summary'
    required: false
    default: 'false'
runs:
  using: 'node12'
  main: 'dist/index.js'
