name: Test Clair publish Scan
on: [push]

jobs:
  publish-report:
    name: Publis Clair report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Publish Clair Scan
        uses: ./
        with:
          report_paths: assets/clair-report/without-securityLevel-vulnerabilities.json
          #publish_summary: true
          severity_level: 'High'




