name: Test Clair publish Scan
on: [push]

jobs:
  publish-report:
    name: Publis Clair report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Publish Clair Scan
        uses: ./
        with:
          report_paths: assets/clair-report/test-without-vulnerabilities.json
          check_name: ' 📄  Results Clair Scan'
          summary: 'Results Clair Scan for image ubuntu-14.04.local'
          #severity_level: 'High'
