name: Test Clair publish Scan
on: [push]

jobs:
  publish-report:
    name: Publis Clair report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Publish Clair Scan
        uses: ./
        with:
          report_paths: assets/clair-report/ubu*.json
          publish_summary: 'true'
          severity_level: 'High'
          fail_with_vulnerabilities: 'true'
  upload-logs-to-elastic:
    runs-on: ubuntu-latest
    needs: [publish-report]
    if: always()
    steps:
    - name: Upload GitHub Action workflows logs to elastic
      uses: jbenaventem/upload-github-workflow-logs-to-elastic@main
      with:
        github_token: "${{ secrets.BNAUK_TOKEN }}"
        github_org: "benauca"
        github_repository: "pubish-clair-report"
        github_run_id: "${{ github.run_id }}"
        elastic_host: "${{ secrets.ELASTIC_HOST }}"
        elastic_api_key_id: "${{ secrets.ELASTIC_KEY_ID }}"
        elastic_api_key: "${{ secrets.ELASTIC_API_KEY }}"
        elastic_index: "ci-cd"




